--SQL file
INSERT INTO MEDICO_ENTITY (ID, NOMBRE, APELLIDO, ESPECIALIDAD, REGISTRO) VALUES (100, 'Fernanda', 'Gomez', 'neuro', 'x');
INSERT INTO MEDICO_ENTITY (ID, NOMBRE, APELLIDO, ESPECIALIDAD, REGISTRO) VALUES (105, 'Daniela', 'Espinosa', 'cardio', 'y');
INSERT INTO MEDICO_ENTITY (ID, NOMBRE, APELLIDO, ESPECIALIDAD, REGISTRO) VALUES (45, 'Juan', 'Arias', 'ginec', 'z');

SELECT * FROM MEDICO_ENTITY 